Fix null pointer exception casued by measurements values and measureSchemas values are not consistent (#15532)
* fix the problem of null pointer below:
 NullPointerException: Cannot invoke "org.apache.tsfile.write.schema.MeasurementSchema.serializeTo(java.io.OutputStream)" because "this.measurementSchemas[i]" is null

* fix the problem of null pointer for table model below:
 NullPointerException: Cannot invoke "org.apache.tsfile.write.schema.MeasurementSchema.serializeTo(java.io.OutputStream)" because "this.measurementSchemas[i]" is null